(ns harness.setup.skills-test
  "The fifth part: the shipped skills, their citations held to the method,
  and the two renderings held to the source."
  (:require
   [babashka.fs :as fs]
   [clojure.string :as str]
   [clojure.test :refer [deftest is testing]]
   [harness.setup.skills :as skills]))

(def kit-dir (str (fs/parent (fs/real-path "."))))

(deftest the-four-skills-ship-in-the-one-anatomy
  (is (= ["plan" "scoping" "stage-end" "stage-plan"] (skills/shipped kit-dir)))
  (doseq [nm (skills/shipped kit-dir)
          :let [text (slurp (skills/source-path kit-dir nm))
                [fm body] (skills/split-frontmatter text)]]
    (is (re-find (re-pattern (str "(?m)^name: " nm "$")) fm) (str nm ": the frontmatter names it"))
    (is (re-find #"(?m)^description: .{40,}" fm) (str nm ": a description Claude Code triggers on"))
    (is (= ["## When it runs" "## Reads" "## Refuses when" "## Asks" "## Writes" "## Done when"]
           (filterv #(str/starts-with? % "## ") (str/split-lines body)))
        (str nm ": the six sections, in the one order"))
    (is (seq (skills/citations text)) (str nm ": it cites what it reads"))
    (is (str/includes? body "`bb next`") (str nm ": it ends by saying what comes next"))))

(deftest every-citation-holds-in-this-kit
  ;; The method is the source; a skill cites its headings, and the gates hold
  ;; them to the file - renamed is fine, renamed out from under a skill is not.
  (doseq [nm (skills/shipped kit-dir)]
    (is (= [] (skills/citation-problems kit-dir nm (slurp (skills/source-path kit-dir nm)))) nm)))

(deftest a-citation-is-a-file-and-a-heading-it-carries
  (let [text "## Reads\n\n| File | Heading |\n|---|---|\n| `method.md` | `Step 0 — Scoping, before anything is set up` |\n| `method.md` | `No such heading` |\n| `nowhere.md` | `Anything` |\n\n| Other | Table |\n|---|---|\n| a | b |\n"]
    (is (= [["method.md" "Step 0 — Scoping, before anything is set up"] ["method.md" "No such heading"] ["nowhere.md" "Anything"]]
           (skills/citations text))
        "the Reads table only, backticks stripped")
    (is (= ["skills/x/SKILL.md cites the heading \"No such heading\" of method.md, which the file no longer carries"
            "skills/x/SKILL.md cites nowhere.md, which is not in the KIT"]
           (skills/citation-problems kit-dir "x" text)))
    (is (skills/heading? "# A\n\n### Step 0 — Scoping, before anything is set up\n" "Step 0 — Scoping, before anything is set up"))
    (is (not (skills/heading? "Step 0 — Scoping in prose" "Step 0 — Scoping")) "a heading, not a mention")))

(deftest a-rendering-is-the-source-with-one-note-and-the-commit-is-not-compared
  (let [source "---\nname: x\ndescription: d\n---\n\n# X\n\nbody\n"
        r (skills/render "x" source "abc1234")]
    (is (str/starts-with? r "---\nname: x\ndescription: d\n---\n<!-- GENERATED by bb skills-sync from the KIT's skills/x/SKILL.md - edit it there, never here. KIT commit: abc1234 -->\n\n# X\n\nbody\n"))
    (is (skills/generated? r))
    (is (not (skills/generated? source)))
    (is (= source (skills/normalize r)) "the note is the one difference")
    (is (skills/current? r source))
    (is (skills/current? (skills/render "x" source "def5678") source) "another commit in the note is still current")
    (is (skills/current? (skills/render "x" source nil) source) "the clone's own, with no commit")
    (is (not (skills/current? source source)) "the source itself is not a rendering: it has no note")
    (is (not (skills/current? (skills/render "x" (str source "more\n") "abc") source)) "a changed body is drift")
    (is (str/includes? (skills/render "x" source nil) "KIT commit: HEAD, this clone's own"))))

(deftest the-sync-writes-the-renderings-checks-them-and-leaves-a-projects-own-skill-alone
  (let [target (str (fs/create-temp-dir {:prefix "skills-"}))
        own (fs/path target skills/target-dir "mine" "SKILL.md")]
    (fs/create-dirs (fs/parent own))
    (spit (str own) "---\nname: mine\n---\nthe project's own\n")
    (testing "check before anything is written: every skill missing"
      (let [rs (skills/sync! kit-dir target :check? true)]
        (is (= (skills/shipped kit-dir) (mapv :name rs)))
        (is (every? :changed? rs))
        (is (not-any? :existed? rs))
        (is (not (fs/exists? (fs/path target skills/target-dir "scoping" "SKILL.md"))) "check writes nothing")))
    (testing "written, with the commit in the note"
      (let [rs (skills/sync! kit-dir target :commit "abc1234")]
        (is (every? :changed? rs))
        (let [text (slurp (str (fs/path target skills/target-dir "scoping" "SKILL.md")))]
          (is (str/includes? text "KIT commit: abc1234"))
          (is (str/starts-with? text "---\nname: scoping\n") "the frontmatter stays first, so Claude Code reads it"))))
    (testing "current after, whatever commit a later check would name"
      (is (not-any? :changed? (skills/sync! kit-dir target :check? true :commit "zzz9999"))))
    (testing "an edited copy is drift; the sync restores it"
      (let [path (str (fs/path target skills/target-dir "plan" "SKILL.md"))]
        (spit path (str (slurp path) "\nedited here\n"))
        (is (= ["plan"] (mapv :name (filter :changed? (skills/sync! kit-dir target :check? true)))))
        (skills/sync! kit-dir target :commit "abc1234")
        (is (not (str/includes? (slurp path) "edited here")))))
    (is (= "---\nname: mine\n---\nthe project's own\n" (slurp (str own))) "a project's own skill is never touched")))
